<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>SimpleASTInterpreter.Instructions</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\SimpleASTInterpreter.Core\SimpleASTInterpreter.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Update="instructions.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
